name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    # hw1
    # - name: Build hw1
    #   run: pushd hw1_tree && go build -v ./...

    - name: Test hw1
      run: pushd hw1_tree && go test -v ./...

    # hw2
    # - name: Build hw2
    #   run: pushd hw2_signer && go build -v ./...

    - name: Test hw2
      run: pushd hw2_signer && go test -v ./...

    # hw3
    # - name: Build hw3
    #   run: pushd hw3_bench && go build -v ./...

    - name: Test hw3
      run: pushd hw3_bench && go test -v ./...

    # hw4
    # - name: Build hw4
    #   run: pushd hw4_test_coverage && go build -v ./...

    - name: Test hw4
      run: pushd hw4_test_coverage && go test -v ./...

    # hw5
    # - name: Build hw5
    #   run: pushd hw5_codegen && go build -v ./...

    - name: Test hw5
      run: pushd hw5_codegen && go test -v ./...

    # hw6
    # - name: Build hw6
    #   run: pushd hw6_db_explorer && go build -v ./...

    - name: Test hw6
      run: pushd hw6_db_explorer && go test -v ./...
